[toolchain]
# Current rust version for mozilla-central
# https://firefox-source-docs.mozilla.org/writing-rust-code/update-policy.html
channel = "1.73.0"
components = ["rustfmt", "clippy", "rust-analyzer"]
